#!/bin/bash

# Script to configure PaliGemma2 in the OCR application
# This sets up the application to use the downloaded PaliGemma2 model files

set -e  # Exit on errors

COMBINED_MODEL_DIR="./models/paligemma2/combined"
GOOGLE_MODEL_DIR="./models/paligemma2/google"
ONNX_MODEL_DIR="./models/paligemma2/onnx"

echo "🔧 Configuring PaliGemma2 for OCR Application"
echo "============================================="

# Check if model files exist
if [ ! -d "$COMBINED_MODEL_DIR" ]; then
    echo "❌ Error: Combined model directory not found: $COMBINED_MODEL_DIR"
    echo "Please run download-paligemma2-full.sh or download-paligemma2-onnx-community.sh first."
    exit 1
fi

# Check for essential model files
ESSENTIAL_FILES=(
    "decoder_model_merged_quantized.onnx"
    "vision_encoder_quantized.onnx"
    "tokenizer.json"
    "config.json"
)

MISSING_FILES=0
for file in "${ESSENTIAL_FILES[@]}"; do
    if [ ! -f "${COMBINED_MODEL_DIR}/${file}" ]; then
        echo "❌ Missing essential file: ${file}"
        MISSING_FILES=$((MISSING_FILES + 1))
    fi
done

if [ $MISSING_FILES -gt 0 ]; then
    echo "⚠️ Warning: Some essential files are missing. The model may not work correctly."
    echo "Try running download-paligemma2-onnx-community.sh to get all required files."
    echo "Continuing configuration anyway..."
fi

# Update the paligemma2-simple.js file to use the local model files
echo "📝 Updating paligemma2-simple.js to use local model files..."

cat > ./lib/paligemma2-simple-config.js << 'EOF'
/**
 * Configuration for PaliGemma2 model
 * This file is auto-generated by configure-paligemma2.sh
 */

import path from 'path';
import fs from 'fs';

const COMBINED_DIR = path.join(process.cwd(), 'models', 'paligemma2', 'combined');
const ONNX_DIR = path.join(process.cwd(), 'models', 'paligemma2', 'onnx');
const GOOGLE_DIR = path.join(process.cwd(), 'models', 'paligemma2', 'google');

// Helper to get the best available model file from multiple locations
const findBestModelFile = (filename, alternativeNames = []) => {
  // Try combined dir first
  if (fs.existsSync(path.join(COMBINED_DIR, filename))) {
    return path.join(COMBINED_DIR, filename);
  }
  
  // Try alternatives in combined dir
  for (const altName of alternativeNames) {
    if (fs.existsSync(path.join(COMBINED_DIR, altName))) {
      return path.join(COMBINED_DIR, altName);
    }
  }
  
  // Try ONNX dir
  if (fs.existsSync(path.join(ONNX_DIR, filename))) {
    return path.join(ONNX_DIR, filename);
  }
  
  // Try alternatives in ONNX dir
  for (const altName of alternativeNames) {
    if (fs.existsSync(path.join(ONNX_DIR, altName))) {
      return path.join(ONNX_DIR, altName);
    }
  }
  
  // Return null if not found
  return null;
};

// Check which model files are available
const hasDecoderModelQuantized = findBestModelFile('decoder_model_merged_quantized.onnx') !== null;
const hasVisionEncoderQuantized = findBestModelFile('vision_encoder_quantized.onnx') !== null;
const hasModelOnnx = findBestModelFile('model.onnx') !== null;

// Log available model files
console.log('PaliGemma2 model files availability:');
console.log(`- decoder_model_merged_quantized.onnx: ${hasDecoderModelQuantized ? 'FOUND' : 'NOT FOUND'}`);
console.log(`- vision_encoder_quantized.onnx: ${hasVisionEncoderQuantized ? 'FOUND' : 'NOT FOUND'}`);
console.log(`- model.onnx: ${hasModelOnnx ? 'FOUND' : 'NOT FOUND'}`);

export const MODEL_CONFIG = {
  // Model IDs for remote loading (fallbacks)
  MODEL_ID: "NSTiwari/paligemma2-3b-mix-224-onnx", // Primary fallback
  ONNX_COMMUNITY_MODEL_ID: "onnx-community/paligemma2-3b-pt-224", // Secondary fallback
  
  // Local paths for model files
  LOCAL_MODEL_DIR: COMBINED_DIR,
  ONNX_MODEL_DIR: ONNX_DIR,
  GOOGLE_MODEL_DIR: GOOGLE_DIR,
  
  // Model file paths (with automatic detection of best available files)
  MODEL_FILES: {
    // Configuration files
    config: findBestModelFile('config.json') || "config.json",
    preprocessorConfig: findBestModelFile('preprocessor_config.json') || "preprocessor_config.json",
    tokenizerConfig: findBestModelFile('tokenizer_config.json') || "tokenizer_config.json",
    generationConfig: findBestModelFile('generation_config.json') || "generation_config.json",
    specialTokensMap: findBestModelFile('special_tokens_map.json') || "special_tokens_map.json",
    vocab: findBestModelFile('vocab.json') || "vocab.json",
    tokenizer: findBestModelFile('tokenizer.json') || "tokenizer.json",
    
    // Model files (with fallbacks)
    model: findBestModelFile('model.onnx', ['decoder_model_merged_quantized.onnx']) || "model.onnx",
    decoderModelMerged: findBestModelFile('decoder_model_merged_quantized.onnx', 
      ['decoder_model_merged_uint8.onnx', 'decoder_model_merged_int8.onnx', 'decoder_model_merged_fp16.onnx']) 
      || "decoder_model_merged_quantized.onnx",
    visionEncoder: findBestModelFile('vision_encoder_quantized.onnx',
      ['vision_encoder_uint8.onnx', 'vision_encoder_int8.onnx', 'vision_encoder_fp16.onnx'])
      || "vision_encoder_quantized.onnx"
  },
  
  // Loading options
  LOADING_OPTIONS: {
    quantized: true,
    useLocalFiles: true,
    loadInMemory: false, // Set to false for large models
    enablePipeline: true,
    localFilesAvailable: hasDecoderModelQuantized && hasVisionEncoderQuantized
  }
};

export default MODEL_CONFIG;
EOF

echo "✅ Created PaliGemma2 configuration file"

# Create symlinks for backward compatibility
echo "🔗 Creating symlinks for backward compatibility..."
mkdir -p ./models/paligemma2_onnx
ln -sf ../paligemma2/combined/model.onnx ./models/paligemma2_onnx/model.onnx 2>/dev/null || true
ln -sf ../paligemma2/combined/decoder_model_merged_quantized.onnx ./models/paligemma2_onnx/decoder_model_merged_quantized.onnx 2>/dev/null || true
ln -sf ../paligemma2/combined/vision_encoder_quantized.onnx ./models/paligemma2_onnx/vision_encoder_quantized.onnx 2>/dev/null || true

# Update the .env file to use local model files
echo "📝 Updating environment configuration..."
if [ -f .env ]; then
    if ! grep -q "PALIGEMMA2_MODEL_PATH" .env; then
        echo "PALIGEMMA2_MODEL_PATH=./models/paligemma2/combined" >> .env
        echo "PALIGEMMA2_USE_LOCAL=true" >> .env
        echo "PALIGEMMA2_ONNX_COMMUNITY_MODEL=true" >> .env
        echo "✅ Added PaliGemma2 configuration to .env"
    else
        echo "⚠️ PaliGemma2 configuration already exists in .env"
        # Update the values
        sed -i 's|^PALIGEMMA2_MODEL_PATH=.*|PALIGEMMA2_MODEL_PATH=./models/paligemma2/combined|' .env
        sed -i 's|^PALIGEMMA2_USE_LOCAL=.*|PALIGEMMA2_USE_LOCAL=true|' .env
        if ! grep -q "PALIGEMMA2_ONNX_COMMUNITY_MODEL" .env; then
            echo "PALIGEMMA2_ONNX_COMMUNITY_MODEL=true" >> .env
        else
            sed -i 's|^PALIGEMMA2_ONNX_COMMUNITY_MODEL=.*|PALIGEMMA2_ONNX_COMMUNITY_MODEL=true|' .env
        fi
    fi
else
    echo "PALIGEMMA2_MODEL_PATH=./models/paligemma2/combined" > .env
    echo "PALIGEMMA2_USE_LOCAL=true" >> .env
    echo "PALIGEMMA2_ONNX_COMMUNITY_MODEL=true" >> .env
    echo "✅ Created .env with PaliGemma2 configuration"
fi

echo
echo "✅ PaliGemma2 configuration completed"
echo "----------------------------------"
echo "The OCR application is now configured to use the downloaded PaliGemma2 model files."
echo "Model path: $COMBINED_MODEL_DIR"
echo
echo "To apply these changes to the application, restart the server:"
echo "npm run start:no-warnings"
echo "or"
echo "./start-no-warnings.sh"
